# Generated by Django 4.1.3 on 2023-05-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='College',
            field=models.CharField(choices=[('ABES Engineering College Ghaziabad', 'ABES Engineering College Ghaziabad')], default='None', max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
