# Generated by Django 4.1.3 on 2023-06-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0002_alter_user_college_alter_user_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Phone',
            field=models.CharField(max_length=10),
        ),
    ]
