# Generated by Django 4.1.3 on 2023-06-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0004_alter_user_linkedin_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='LinkedIn',
            field=models.CharField(blank=True, default=False, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Phone',
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
    ]
